author = Artur Tarassow
email = atecon@posteo.de
version = 0.3
date = 2023-03-20
description = Write matrix as Latex table
tags = C88
min-version = 2021a
public = latextab
help = latextab_help.txt
sample-script = latextab_sample.inp
data-requirement = no-data-ok
