author = Artur Tarassow
email = atecon@posteo.de
version = 1.1
date = 2023-07-28
description = Write matrix as Latex table
tags = C88
min-version = 2021a
public = latextab
help = latextab_help.md
sample-script = latextab_sample.inp
data-requirement = no-data-ok
